### ISSUE TITLE
Error with pip install command

### ISSUE THREAD

**Issue by shubhambanavalikar** [sign-language-processing/signwriting-animation#2]
When running pip install git+https://github.com/sign-language-processing/signwriting-animation, I get the following error:

ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must not contain {'dev'} properties

I would appreciate some help with understanding how to fix this. Thank you in advance for your help!

**Comment by duongcongnha** [comment]
can not install too, have tried install from local. May be missing `setup.py` file ??

**Comment by AmitMY** [comment]
fixed in https://github.com/sign-language-processing/signwriting-animation/commit/8c1f8cecfb7a9b62cd5fc8d0f21b742d8f5aed49
however, please understand that this repository is a work in progress, and animating signwriting does not currently work
